services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: db
    environment:
      - ORACLE_SID=FREE
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_PWD=Oracle_123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/back
    expose:
      - "1521"
    restart: always
  tomee:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
volumes:
  oracle-data:
  oracle-backup: